project_id = "hhioqglejbjcqcmqqsnj"

[functions.merchant-api]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = false

[functions.seed-users]
verify_jwt = false

[functions.process-settlement]
verify_jwt = false

[functions.oxapay-webhook]
verify_jwt = false

[functions.webhook-retry]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.create-deposit-intent]
verify_jwt = false

[functions.get-deposit-status]
verify_jwt = false

[functions.create-agent-with-user]
verify_jwt = false

[functions.create-merchant-with-user]
verify_jwt = false

[functions.create-merchant-for-agent]
verify_jwt = false

[functions.manage-merchant]
verify_jwt = false
